site_name: 小巩的网站    

theme:  
  name: 'mkdocs' 
  feature:
    tabs: true   
  palette:
    primary: 'light green'
    accent: 'green'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  logo:
    icon: 'cloud'
  language: 'zh'  

extra:
  search:
    language: 'jp'

  social:  
    - type: 'github'
      link: 'https://github.com/gongluis'  
      

nav:   

  - 介绍: index.md
  - 音视频: 
         - mp4文件解析: AnalysisMp4File.md
         - mp4文件加解密思考: encodeMp4.md 
         - mp4文件抽帧方法总结: crowdSourcing.md   
  - JAVA: 
         - 基础数据类型: basicDataType.md
         - 算法: algorithm.md
         - 垃圾回收机制: garbage.md
         - 线程: thread.md
         - 线程池: threadPool.md
         - 集合: collection.md
  - sdk笔记: 
         - provider方式: sdk_provider.md 
         - 总结: sdk.md 
         - 进程间通信sdk: ipc.md          
  - Android: 
         - 四大组件: fourcomponent.md    
         - 设计模式:
            - 单例: designpattern/singleInstance.md
            - 工厂: designpattern/factory.md
            - Builder: designpattern/builder.md
            - 观察者: designpattern/observer.md
         - 自定义控件:
            - 自定义组合控件: customView/customCombinationView.md
            - 自定义View: customView/customView.md
         - APP架构:  
            - MVC:  constructure/mvc.md      
            - MVP: constructure/font_updown.md
            - MVvm: constructure/font_updown.md 
         - 事件分发: touchEvent.md
         - Handler原理: handler.md
         - Android版本对应SDK版本: sdkversion.md
         - APP整体优化: better.md
         - APP启动流程: app_start_process.md
         - 屏幕适配: adaption.md
         - 一些小的点:
            - ConText: context.md
         - 一些常见功能的思考:
            - 登录: login.md
         - 单元测试Monkey: test.md
  - Flutter插件: 
         - 什么是flutter插件及作用: whyflutterplugin.md 
         - 如何配置flutter环境: howflutterenvironment.md 
         - flutter插件开发: flutterplugincoding.md 
  - git: 
         - 常见场景操作: git_scenes.md   
         - Android端git版本管理: git_client_steps.md  
         - commit log: git_commit_log.md 
  - 故障复盘记录: 
         - AndroidSDK故障记录: sdkexception.md 
                    

